name: Generate Javadocs

on:
  push:
    branches:
      - main
      - ci

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Generate Javadocs
        run: |
          mkdir -p javadocs
          javadoc -encoding ISO-8859-1 -docencoding UTF-8 -charset UTF-8 \
            -d javadocs -sourcepath src -subpackages com.fs.starfarer.api \
            -classpath "StarsectorJarsPrivate/*" -quiet -Xdoclint:none

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: javadocs
